server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      routes:
        - id: common-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/common/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
