server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: JwtAuthenticationFilter
      routes:
        - id: common-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/common/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**

jwt:
  secret: ${JWT_SECRET}
  ignore-paths:
    - /api/user/auth
